# Lab 4-2: Load Data

Author: Seungjae Lee (이승재)

<div class="alert alert-warning">
    We use elemental PyTorch to implement linear regression here. However, in most actual applications, abstractions such as <code>nn.Module</code> or <code>nn.Linear</code> are used.
</div>

## Slicing 1D Array

In [ ]:
nums = [0, 1, 2, 3, 4]

In [ ]:
print(nums)

[0, 1, 2, 3, 4]


index 2에서 4 전까지 가져와라. (앞 포함, 뒤 비포함)

In [ ]:
print(nums[2:4])

[2, 3]


index 2부터 다 가져와라.

In [ ]:
print(nums[2:])

[2, 3, 4]


index 2 전까지 가져와라. (역시 뒤는 비포함)

In [ ]:
print(nums[:2])

[0, 1]


전부 가져와라

In [ ]:
print(nums[:])

[0, 1, 2, 3, 4]


마지막 index 전까지 가져와라. (뒤는 비포함!)

In [ ]:
print(nums[:-1])

[0, 1, 2, 3]


assign 도 가능!

In [ ]:
nums[2:4] = [8, 9]

In [ ]:
print(nums)

[0, 1, 8, 9, 4]


## Slicing 2D Array

In [ ]:
import numpy as np

In [ ]:
b = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [ ]:
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
b[:, 1]

array([ 2,  6, 10])

In [ ]:
b[-1]

array([ 9, 10, 11, 12])

In [ ]:
b[-1, :]

array([ 9, 10, 11, 12])

In [ ]:
b[-1, ...]

array([ 9, 10, 11, 12])

In [ ]:
b[0:2, :]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
b= np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])

Q1. 위 배열을 이용해 [1 4 7 10]을 출력해보세요.

Q2. 위 배열을 이용해 11을 출력해보세요.

Q3. 위 배열을 이용해 [[ 8  9]
 [11 12]]을 출력해보세요.

Q4. 위 배열을 이용해 [[ 2  3]
 [ 5  6]
 [ 8  9]
 [11 12]]을 출력해보세요.

 Q5. 위 배열을 이용해 [10 11 12]을 출력해보세요.

In [ ]:
print(b[:, 0])
print(b[3, 1])
print(b[2:, 1:])
print(b[:, 1:])
print(b[3, :])

[ 1  4  7 10]
11
[[ 8  9]
 [11 12]]
[[ 2  3]
 [ 5  6]
 [ 8  9]
 [11 12]]
[10 11 12]


## Loading Data from `.csv` file

data-01-test-score.csv 파일 사용!

In [ ]:
import numpy as np

Drive mount 하는 방법

https://vision-ai.tistory.com/entry/%EC%BD%94%EB%9E%A9%EC%97%90%EC%84%9C-%EB%93%9C%EB%9D%BC%EC%9D%B4%EB%B8%8C%EC%9D%98-csv-%ED%8C%8C%EC%9D%BC-%EC%9D%BD%EA%B8%B0

을 참고하세요!!

In [ ]:
from google.colab import drive

In [ ]:
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
xy= np.loadtxt('/content/drive/MyDrive/data-01-test-score.csv',delimiter=',', dtype=np.float32)

In [ ]:
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

In [ ]:
print(x_data.shape) # x_data shape
print(len(x_data))  # x_data 길이
print(x_data[:5])   # 첫 다섯 개

(25, 3)
25
[[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]]


In [ ]:
print(y_data.shape) # y_data shape
print(len(y_data))  # y_data 길이
print(y_data[:5])   # 첫 다섯 개

(25, 1)
25
[[152.]
 [185.]
 [180.]
 [196.]
 [142.]]


## Imports

In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [ ]:
# For reproducibility
torch.manual_seed(1)

## Low-level Implementation

In [ ]:
# 데이터
x_train = torch.FloatTensor(x_data)
y_train = torch.FloatTensor(y_data)
# 모델 초기화
W = torch.zeros((3,1), requires_grad=True) #가중치 W를 0으로 초기화하고 학습을 통해 값이 변경될 수 있도록 하세요. x_train의 shape을 잘 생각해보세요!!
b = torch.zeros(1, requires_grad=True) #가중치 W를 0으로 초기화하고 학습을 통해 값이 변경될 수 있도록 하세요.
# optimizer 설정
optimizer = optim.SGD([W,b], lr=1e-5) #SGD optimizer를 사용하고 learning rate는 1e-5로 적용하세요.

nb_epochs = 20
for epoch in range(nb_epochs + 1):
    
    # H(x) 계산
    hypothesis = x_train.matmul(W) + b #x_train의 shape이 달라졌기 때문에 행렬곱셉을 합니다!!

    # cost 계산
    cost = torch.mean((hypothesis - y_train) ** 2)#파이토치 코드 상으로 선형 회귀의 비용 함수에 해당되는 평균 제곱 오차를 선언하세요.

    # cost로 H(x) 개선
    optimizer.zero_grad()  # gradient를 0으로 초기화
    cost.backward()  # 비용 함수를 미분하여 gradient 계산
    optimizer.step() # W와 b를 업데이트

    # 100번마다 로그 출력
    print('Epoch {:4d}/{} Cost: {:.6f}'.format(
        epoch, nb_epochs, cost.item()
    ))

Epoch    0/20 Cost: 26811.960938
Epoch    1/20 Cost: 9920.530273
Epoch    2/20 Cost: 3675.298340
Epoch    3/20 Cost: 1366.260498
Epoch    4/20 Cost: 512.542480
Epoch    5/20 Cost: 196.896637
Epoch    6/20 Cost: 80.190987
Epoch    7/20 Cost: 37.038696
Epoch    8/20 Cost: 21.081343
Epoch    9/20 Cost: 15.178760
Epoch   10/20 Cost: 12.993679
Epoch   11/20 Cost: 12.183023
Epoch   12/20 Cost: 11.880535
Epoch   13/20 Cost: 11.765958
Epoch   14/20 Cost: 11.720851
Epoch   15/20 Cost: 11.701438
Epoch   16/20 Cost: 11.691514
Epoch   17/20 Cost: 11.685116
Epoch   18/20 Cost: 11.680005
Epoch   19/20 Cost: 11.675380
Epoch   20/20 Cost: 11.670952


## High-level Implementation with `nn.Module`

In [ ]:
class MultivariateLinearRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(3, 1)

    def forward(self, x):
        return self.linear(x)

In [ ]:
# 데이터
x_train = torch.FloatTensor(x_data)
y_train = torch.FloatTensor(y_data)
# 모델 초기화
model = MultivariateLinearRegressionModel() #MultivariateLinearRegressionModel()로 모델을 초기화하세요.
# optimizer 설정
optimizer = optim.SGD(model.parameters(), lr=1e-5)  #SGD optimizer를 사용하고 learning rate는 1e-5로 적용하세요.

nb_epochs = 20
for epoch in range(nb_epochs+1):
    
    # H(x) 계산
    prediction = model(x_train) #모델을 생성해서 예측값을 구해보세요.
    
    # cost 계산
    cost = F.mse_loss(prediction, y_train)#PyTorch에서 기본적으로 제공하는 mse 함수를 사용하세요.
    
    # cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    # 20번마다 로그 출력
    print('Epoch {:4d}/{} Cost: {:.6f}'.format(
        epoch, nb_epochs, cost.item()
    ))

Epoch    0/20 Cost: 28693.490234
Epoch    1/20 Cost: 10618.750000
Epoch    2/20 Cost: 3936.015381
Epoch    3/20 Cost: 1465.219727
Epoch    4/20 Cost: 551.693726
Epoch    5/20 Cost: 213.934616
Epoch    6/20 Cost: 89.052269
Epoch    7/20 Cost: 42.876007
Epoch    8/20 Cost: 25.799639
Epoch    9/20 Cost: 19.482420
Epoch   10/20 Cost: 17.143093
Epoch   11/20 Cost: 16.274508
Epoch   12/20 Cost: 15.949721
Epoch   13/20 Cost: 15.825986
Epoch   14/20 Cost: 15.776565
Epoch   15/20 Cost: 15.754660
Epoch   16/20 Cost: 15.742919
Epoch   17/20 Cost: 15.734917
Epoch   18/20 Cost: 15.728307
Epoch   19/20 Cost: 15.722219
Epoch   20/20 Cost: 15.716357


## Dataset and DataLoader

<div class="alert alert-warning">
    pandas 기초지식이 필요할 것 같다
</div>

너무 데이터가 크면 `x_data`, `y_data` 를 전부 다 가져오지 말고, 필요한 배치만 가져올 수 밖에 없다.

[PyTorch Data Loading and Processing tutorial](https://pytorch.org/tutorials/beginner/data_loading_tutorial.html#iterating-through-the-dataset)